version: '3'

volumes:
  production_postgres_data: {}
  production_postgres_data_backups: {}
  production_traefik: {}

services:
  django: &django
    image: docker.pkg.github.com/dzieje-khorinis/translations-tool/translation-tool-backend:latest
    depends_on:
      - postgres
      - redis
    env_file:
      - ./.envs/.production/.django
      - ./.envs/.production/.postgres
    command: /start

  postgres:
    image: docker.pkg.github.com/dzieje-khorinis/translations-tool/translation-tool-db:latest
    volumes:
      - production_postgres_data:/var/lib/postgresql/data:Z
      - production_postgres_data_backups:/backups:z
    env_file:
      - ./.envs/.production/.postgres

  traefik:
    image: docker.pkg.github.com/dzieje-khorinis/translations-tool/translation-tool-router:latest
    depends_on:
      - django
    volumes:
      - production_traefik:/etc/traefik/acme:z
      - ./compose/production/traefik/traefik-https-example.yml:/etc/traefik/traefik.yml
    ports:
      - "80:80"
      - "443:443"

  redis:
    image: redis:5.0

  celeryworker:
    <<: *django
    command: /start-celeryworker

  celerybeat:
    <<: *django
    command: /start-celerybeat

  flower:
    <<: *django
    command: /start-flower
