# Generated by Django 3.1.5 on 2022-09-18 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_user_last_active_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role_related_language',
            field=models.CharField(blank=True, choices=[('en', 'English'), ('pl', 'Polish'), ('de', 'German'), ('ru', 'Russian'), ('cs', 'Czech'), ('it', 'Italian')], max_length=2),
        ),
    ]
