# Generated by Django 3.1.5 on 2021-01-17 19:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TranslationGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_en', models.CharField(blank=True, max_length=255)),
                ('name_pl', models.CharField(blank=True, max_length=255)),
                ('name_de', models.CharField(blank=True, max_length=255)),
                ('name_ru', models.CharField(blank=True, max_length=255)),
                ('order_index', models.IntegerField(default=0)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='translations.translationgroup')),
            ],
        ),
        migrations.CreateModel(
            name='Translation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.TextField(db_index=True, max_length=2000)),
                ('value_en', models.TextField(blank=True, max_length=2000)),
                ('value_pl', models.TextField(blank=True, max_length=2000)),
                ('value_de', models.TextField(blank=True, max_length=2000)),
                ('value_ru', models.TextField(blank=True, max_length=2000)),
                ('state_en', models.CharField(choices=[('NEW', 'New'), ('TODO', 'To do'), ('READY_TO_REVIEW', 'Ready to review'), ('NEEDS_WORK', 'Needs work'), ('ACCEPTED', 'Accepted')], default='NEW', max_length=255)),
                ('state_pl', models.CharField(choices=[('NEW', 'New'), ('TODO', 'To do'), ('READY_TO_REVIEW', 'Ready to review'), ('NEEDS_WORK', 'Needs work'), ('ACCEPTED', 'Accepted')], default='NEW', max_length=255)),
                ('state_de', models.CharField(choices=[('NEW', 'New'), ('TODO', 'To do'), ('READY_TO_REVIEW', 'Ready to review'), ('NEEDS_WORK', 'Needs work'), ('ACCEPTED', 'Accepted')], default='NEW', max_length=255)),
                ('state_ru', models.CharField(choices=[('NEW', 'New'), ('TODO', 'To do'), ('READY_TO_REVIEW', 'Ready to review'), ('NEEDS_WORK', 'Needs work'), ('ACCEPTED', 'Accepted')], default='NEW', max_length=255)),
                ('order_index', models.IntegerField(default=0)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='translations.translationgroup')),
            ],
        ),
        migrations.CreateModel(
            name='HistoricalTranslationGroup',
            fields=[
                ('id', models.IntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('name_en', models.CharField(blank=True, max_length=255)),
                ('name_pl', models.CharField(blank=True, max_length=255)),
                ('name_de', models.CharField(blank=True, max_length=255)),
                ('name_ru', models.CharField(blank=True, max_length=255)),
                ('order_index', models.IntegerField(default=0)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('parent', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='translations.translationgroup')),
            ],
            options={
                'verbose_name': 'historical translation group',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalTranslation',
            fields=[
                ('id', models.IntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('key', models.TextField(db_index=True, max_length=2000)),
                ('value_en', models.TextField(blank=True, max_length=2000)),
                ('value_pl', models.TextField(blank=True, max_length=2000)),
                ('value_de', models.TextField(blank=True, max_length=2000)),
                ('value_ru', models.TextField(blank=True, max_length=2000)),
                ('state_en', models.CharField(choices=[('NEW', 'New'), ('TODO', 'To do'), ('READY_TO_REVIEW', 'Ready to review'), ('NEEDS_WORK', 'Needs work'), ('ACCEPTED', 'Accepted')], default='NEW', max_length=255)),
                ('state_pl', models.CharField(choices=[('NEW', 'New'), ('TODO', 'To do'), ('READY_TO_REVIEW', 'Ready to review'), ('NEEDS_WORK', 'Needs work'), ('ACCEPTED', 'Accepted')], default='NEW', max_length=255)),
                ('state_de', models.CharField(choices=[('NEW', 'New'), ('TODO', 'To do'), ('READY_TO_REVIEW', 'Ready to review'), ('NEEDS_WORK', 'Needs work'), ('ACCEPTED', 'Accepted')], default='NEW', max_length=255)),
                ('state_ru', models.CharField(choices=[('NEW', 'New'), ('TODO', 'To do'), ('READY_TO_REVIEW', 'Ready to review'), ('NEEDS_WORK', 'Needs work'), ('ACCEPTED', 'Accepted')], default='NEW', max_length=255)),
                ('order_index', models.IntegerField(default=0)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('parent', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='translations.translationgroup')),
            ],
            options={
                'verbose_name': 'historical translation',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
