# Generated by Django 3.1.5 on 2021-02-06 22:43

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('translations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicaltranslation',
            name='created_at',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, editable=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='historicaltranslation',
            name='file',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AddField(
            model_name='historicaltranslation',
            name='line',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicaltranslation',
            name='updated_at',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, editable=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='translation',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='translation',
            name='file',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AddField(
            model_name='translation',
            name='line',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='translation',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
