# Generated by Django 3.1.5 on 2021-09-22 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('translations', '0002_auto_20210206_2243'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicaltranslation',
            name='file',
            field=models.CharField(blank=True, db_index=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='translation',
            name='file',
            field=models.CharField(blank=True, db_index=True, max_length=1000),
        ),
    ]
