# Generated by Django 3.1.5 on 2021-09-23 09:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('translations', '0004_directory'),
    ]

    operations = [
        migrations.AddField(
            model_name='directory',
            name='leaf',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='directory',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='translations.directory'),
        ),
    ]
