# Generated by Django 3.1.5 on 2022-09-15 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('translations', '0005_auto_20210923_0957'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicaltranslation',
            name='language',
            field=models.CharField(blank=True, choices=[('en', 'English'), ('pl', 'Polish'), ('de', 'German'), ('ru', 'Russian')], max_length=2),
        ),
    ]
