# Generated by Django 3.1.5 on 2022-09-18 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('translations', '0006_historicaltranslation_language'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='historicaltranslation',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical translation', 'verbose_name_plural': 'historical translations'},
        ),
        migrations.AlterModelOptions(
            name='historicaltranslationgroup',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical translation group', 'verbose_name_plural': 'historical translation groups'},
        ),
        migrations.AddField(
            model_name='historicaltranslation',
            name='state_cs',
            field=models.CharField(choices=[('NEW', 'New'), ('TODO', 'To do'), ('READY_TO_REVIEW', 'Ready to review'), ('NEEDS_WORK', 'Needs work'), ('ACCEPTED', 'Accepted')], default='NEW', max_length=255),
        ),
        migrations.AddField(
            model_name='historicaltranslation',
            name='state_it',
            field=models.CharField(choices=[('NEW', 'New'), ('TODO', 'To do'), ('READY_TO_REVIEW', 'Ready to review'), ('NEEDS_WORK', 'Needs work'), ('ACCEPTED', 'Accepted')], default='NEW', max_length=255),
        ),
        migrations.AddField(
            model_name='historicaltranslation',
            name='value_cs',
            field=models.TextField(blank=True, max_length=2000),
        ),
        migrations.AddField(
            model_name='historicaltranslation',
            name='value_it',
            field=models.TextField(blank=True, max_length=2000),
        ),
        migrations.AddField(
            model_name='historicaltranslationgroup',
            name='name_cs',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='historicaltranslationgroup',
            name='name_it',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='translation',
            name='state_cs',
            field=models.CharField(choices=[('NEW', 'New'), ('TODO', 'To do'), ('READY_TO_REVIEW', 'Ready to review'), ('NEEDS_WORK', 'Needs work'), ('ACCEPTED', 'Accepted')], default='NEW', max_length=255),
        ),
        migrations.AddField(
            model_name='translation',
            name='state_it',
            field=models.CharField(choices=[('NEW', 'New'), ('TODO', 'To do'), ('READY_TO_REVIEW', 'Ready to review'), ('NEEDS_WORK', 'Needs work'), ('ACCEPTED', 'Accepted')], default='NEW', max_length=255),
        ),
        migrations.AddField(
            model_name='translation',
            name='value_cs',
            field=models.TextField(blank=True, max_length=2000),
        ),
        migrations.AddField(
            model_name='translation',
            name='value_it',
            field=models.TextField(blank=True, max_length=2000),
        ),
        migrations.AddField(
            model_name='translationgroup',
            name='name_cs',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='translationgroup',
            name='name_it',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='historicaltranslation',
            name='history_date',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='historicaltranslation',
            name='language',
            field=models.CharField(blank=True, choices=[('en', 'English'), ('pl', 'Polish'), ('de', 'German'), ('ru', 'Russian'), ('cs', 'Czech'), ('it', 'Italian')], max_length=2),
        ),
        migrations.AlterField(
            model_name='historicaltranslationgroup',
            name='history_date',
            field=models.DateTimeField(db_index=True),
        ),
    ]
